#!/usr/bin/env bash

# This script takes atleast one argument
# 1: Domain
# 2: sub-Domain

# Get arguments
domain="$1"
subdomain="$2"

# Check domain for A record
resolve_A_record () {
	local sub="$1"
	local full="${sub}.${domain}"

	ip=$(dig "$full" | awk '/ANSWER SECTION/{getline; print $5}')
	echo "The subdomain $sub is a A record and points to $ip"
}

if [ $# -eq 1 ]; then
	resolve_A_record "www"
	resolve_A_record "lb-01"
	resolve_A_record "web-01"
	resolve_A_record "web-02"
	exit 0
fi

if [ $# -eq 2 ]; then
	resolve_A_record "$subdomain"
	exit 0
fi

echo "Usage: $0 <Domain> <Sub-Domain>"
exit 1
